// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MBSoftware.HorseRacing.Core.DAL
{
    public partial class RaceCard
    {
        public RaceCard()
        {
            RaceCardHorse = new HashSet<RaceCardHorse>();
        }

        public int RaceCardId { get; set; }
        public DateTime RaceDate { get; set; }
        public string RaceTime { get; set; }
        public string RaceName { get; set; }
        public string Going { get; set; }
        public string Distance { get; set; }
        public string Course { get; set; }
        public int RaceClass { get; set; }
        public decimal? PrizeMoney { get; set; }
        public bool Maiden { get; set; }
        public bool Handicap { get; set; }
        public bool Hurdle { get; set; }
        public bool Chase { get; set; }
        public bool Nhf { get; set; }
        public bool Novice { get; set; }
        public bool Beginners { get; set; }
        public string RaceType { get; set; }
        public bool Aw { get; set; }
        public bool Irish { get; set; }
        public string IrishGrade { get; set; }
        public int? Grade { get; set; }

        public virtual ICollection<RaceCardHorse> RaceCardHorse { get; set; }
    }
}