// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MBSoftware.HorseRacing.Core.DAL
{
    public partial class RaceCardHorse
    {
        public int RaceCardHorseId { get; set; }
        public int RaceCardId { get; set; }
        public string HorseName { get; set; }
        public int Age { get; set; }
        public string Trainer { get; set; }
        public string Jockey { get; set; }
        public string JockeyClaim { get; set; }
        public string HeadGear { get; set; }
        public int? Tips { get; set; }
        public int OfficialRating { get; set; }
        public int? Ts { get; set; }
        public int? Rpr { get; set; }
        public string Weight { get; set; }
        public string Odds { get; set; }
        public decimal? DecimalOdds { get; set; }
        public int GoingWins { get; set; }
        public int GoingPlaced { get; set; }
        public int GoingRuns { get; set; }
        public int ClassWins { get; set; }
        public int ClassPlaced { get; set; }
        public int ClassRuns { get; set; }
        public int DistWins { get; set; }
        public int DistPlaced { get; set; }
        public int DistRuns { get; set; }

        public virtual RaceCard RaceCard { get; set; }
    }
}